### ISSUE TITLE
Alsa midi ports

### ISSUE THREAD

**Issue by grammoboy2** [jean-emmanuel/seq192#33]
I've problems restoring the midi connections from seq192 with JACKPatch now and then. This is because the Alsa midi ports seems to change from example 129 to 130. Is this my system or is this a common problem and is there a solution for it?

**Comment by jean-emmanuel** [comment]
129 and 130 sound like midi client numbers, these may indeed change depending on the launch order of the different softwares in use that create alsa midi ports. However I've not experienced patching issues, which I guess makes sense since the patching tool I know of rely on client names and port names instead, not on client numbers and port number ( (I don't use JACKpatch though).

**Comment by jean-emmanuel** [comment]
Closing, feel free to reopen if other informations lead to a problem coming from seq192.
