### ISSUE TITLE
keyboard controls

### ISSUE THREAD

**Issue by coderofsalvation** [jean-emmanuel/seq192#35]
I was just curious, why were the keyboard controls (sequence/group mutes) removed?
I like the OSC-first approach, but is it an idea to somehow support keyboard-control via OSC?
Perhaps a cli-client which sends OSC to the (headless) server? 

**REASON:** I'd like to control headless seq192 via local keyboard. 

> UPDATE: it seems to be pretty easy in c/c++ using liblo

```
#include <stdio.h>
#include <stdlib.h>
#ifndef WIN32
#include <unistd.h>
#endif
#include "lo/lo.h"

int main(int argc, char *argv[])
{
    
    /* an address to send messages to. sometimes it is better to let the server
     * pick a port number for you by passing NULL as the last argument */
//    lo_address t = lo_address_new_from_url( "osc.unix://localhost/tmp/mysocket" );
    lo_address t = lo_address_new(NULL, "7770");

    if (lo_send(t, "/play", NULL) == -1) {
        printf("OSC error %d: %s\n", lo_address_errno(t),
               lo_address_errstr(t));
    }
   return 0
}
```

I'm going to see if I can add in some extra OSC commands, and let you know in case I come up with something interesting.
I can imagine some extra OSC commands in there (without having GUI having to implement/use them necessarily).

**Comment by jean-emmanuel** [comment]
I deliberately removed keyboard control because I wanted to strip it down to the very necessary necessary (an admittedly subjective view). This may sound a bit radical, but as far as I'm concerned seq192 is pretty much feature complete (existing features may be improved though).

The way I see it, keyboard controls are only used for editing, not for perfoming.

**Comment by coderofsalvation** [comment]
makes sense!
closing this issue
